install:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/kvminstall.ps1'))
- set PATH=%USERPROFILE%\.kre\bin;%PATH%
- kvm upgrade
- kvm list

# build and run app
- kpm restore
- kpm build
- dir

build: off
test: off
